### ISSUE TITLE
码表中出现了一些重复出现但缺少注音的汉字条目

### ISSUE THREAD

**Issue by moposx** [lotem/rime-zhung#12]
在码表文件 `zhung.dict.yaml` 中这些条目已经存在一个或者一个以上的读音，但它们仍然继续出现在码表中并缺少对应的拼音标注。
如 “窀”字：
<img width="213" alt="图片" src="https://user-images.githubusercontent.com/15135544/85215961-ba09a900-b3b1-11ea-890f-d8fb05705da1.png">
“墬”字：
<img width="226" alt="图片" src="https://user-images.githubusercontent.com/15135544/85215979-e8878400-b3b1-11ea-8e3c-26b9b21dc4c5.png">
<img width="277" alt="图片" src="https://user-images.githubusercontent.com/15135544/85215982-00f79e80-b3b2-11ea-9e3e-c1a6b60c7f64.png">
“栘”字：
<img width="178" alt="图片" src="https://user-images.githubusercontent.com/15135544/85215986-0f45ba80-b3b2-11ea-896d-dd76dbce09b3.png">

看起来尚不影响该输入方案的使用。这些未注音的汉字条目是否有必要删去？

**Comment by lotem** [comment]
這些未注音的行沒有任何作用，確實應該刪去。

手工製作，比較粗糙，注音也有很多問題。得找個時間更新一下。

**Comment by moposx** [comment]
用脚本筛选了一下，去掉了这些多余的行。我这里已经创建了一个[PR](https://github.com/lotem/rime-zhung/pull/13)可供合并。
另：'箉' 字既没有被注释掉，也没有对应的注音。考虑到这次更改的目的，没有对它进行处理。

**Comment by lotem** [comment]
多謝。已合併PR。
